//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductMaterials = new HashSet<ProductMaterials>();
        }
    
        public int MaterialID { get; set; }
        public int MaterialTypeID { get; set; }
        public int SupplierID { get; set; }
        public string MaterialName { get; set; }
        public string Description { get; set; }
        public int PackageQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal Cost { get; set; }
        public int CurrentStock { get; set; }
        public int MinStockLevel { get; set; }
    
        public virtual MaterialTypes MaterialTypes { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterials> ProductMaterials { get; set; }
    }
}
